name: fucci_rent
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.1
  firebase_storage: ^11.2.6
  firebase_auth: ^4.7.3
  #cloud_firestore: ^4.8.5
  # State managemet
  stacked: ^3.4.1
  stacked_services: ^1.3.0
  google_fonts:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  stacked_generator: ^1.5.0
  build_runner: ^2.4.6

flutter:

  uses-material-design: true
  assets:
    - assets/images/

